replicaCount: 1

namespace: kube-scale

image:
  name: brain
  repository: brain
  tag: latest
  pullPolicy: Never

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

serviceAccount:
  name: brain-service-account

rbac:
  roleName: brain-role
  roleBindingName: brain-rolebinding

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080