name: mltps
namespace: kube-scale
replicaCount: 1

image:
  repository: mltps
  tag: latest
  pullPolicy: IfNotPresent

resources:
  # Minimum resource requests
  requests:
    memory: "256Mi"
    cpu: "100m"
  # Maximum resource requests
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  metricsPort: 8000

livenessProbe:
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10