name: mltps
namespace: kube-scale
replicaCount: 1

image:
  repository: mltps
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  # Maximum resource requests
  limits:
    memory: "2Gi"
    cpu: "2"

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  metricsPort: 8000

livenessProbe:
  path: /health
  initialDelaySeconds: 300
  periodSeconds: 30

readinessProbe:
  path: /health
  initialDelaySeconds: 300
  periodSeconds: 30