apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: traffic-split
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/ingressgateway
  http:
  - match:
    - uri:
        prefix: /s0
    route:
    - destination:
        host: gw-nginx.default.svc.cluster.local
        port:
          number: 80
      weight: 80
    - destination:
        host: gw-nginx-warm-pool.warm-pool.svc.cluster.local
        port:
          number: 80
      weight: 20