apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80
      targetPort: 5000
      name: http
    - port: 8000
      targetPort: 8000
      name: metrics
  type: ClusterIP