apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: brain-controller
  template:
    metadata:
      labels:
        app: brain-controller
    spec:
      containers:
        - name: brain-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
