apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: brain
  template:
    metadata:
      labels:
        app: brain
    spec:
      containers:
        - name: brain
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
