replicaCount: 1

namespace: warm-pool

image:
  repository: msvcbench/microservice
  tag: latest

resources:
  # Minimum resource requests
  requests:
    memory: "128Mi"
    cpu: "50m"
  # Maximum resource limits
  limits:
    memory: "384Mi"
    cpu: "300m"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
  scaleUp:
    stabilizationWindowSeconds: 60
    percentPolicy: 100
    podsPolicy: 1
    periodSeconds: 15
  scaleDown:
    stabilizationWindowSeconds: 120
    percentPolicy: 10
    periodSeconds: 15

config:
  enabled: true
  data:
    APP_ENV: "warm-pool"
    LOG_LEVEL: "info"

service:
  type: NodePort

apps:
  enabled: true
  sApps:
    - name: s0
    - name: s1
    - name: s2

monitoringNamespace: monitoring