replicaCount: 1

namespace: warm-pool

image:
  repository: msvcbench/microservice
  tag: latest

resources:
  # Minimum resource requests
  requests:
    memory: "128Mi"
    cpu: "50m"
  # Maximum resource limits
  limits:
    memory: "500Mi"
    cpu: "500m"

config:
  enabled: true
  data:
    APP_ENV: "warm-pool"
    LOG_LEVEL: "info"

service:
  type: NodePort

apps:
  enabled: true
  sApps:
    - name: s0
    - name: s1
    - name: s2

monitoringNamespace: monitoring