{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warm-pool-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: warm-pool
                port:
                  number: {{ .Values.ingress.servicePort }}
{{- end }}