apiVersion: v1
kind: Service
metadata:
  name: gw-nginx-warm-pool
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    #   nodePort: 31114
      name: http-nginx-wp
  selector:
    app: gw-nginx-warm-pool